Netflix/archaius

archaius-aws/src/main/java/com/netflix/config/sources/AbstractDynamoDbConfigurationSource.java
archaius-aws/src/main/java/com/netflix/config/sources/DynamoDbConfigurationSource.java
archaius-aws/src/main/java/com/netflix/config/sources/DynamoDbDeploymentContextTableCache.java

If requests fails, retry with exponential backoff.
That prevents from cascading failures.
Best practices, according to AWS:
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ErrorHandling.html#APIRetries

Fix, dynamodb should retry with exponential backoff.

---

archaius-core/src/main/java/netflix/archaius/StrInterpolatorFactory.java
archaius-core/src/main/java/netflix/archaius/mapper/ConfigBinder.java
archaius-core/src/main/java/netflix/archaius/mapper/DefaultConfigBinder.java
archaius-core/src/main/java/netflix/archaius/mapper/IoCContainer.java
archaius-core/src/main/java/netflix/archaius/mapper/annotations/Configuration.java
archaius-guice/src/main/java/netflix/archaius/guice/ArchaiusModule.java
archaius-guice/src/test/java/netflix/archaius/guice/ArchaiusModuleTest.java

DI Mapping example,
```java
@Configuration(prefix="foo")
class Foo {
public void setBar(Bar bar);
}
```
```properties
foo.bar=bartype1
```
```java
bind(Bar.class).annotatedWith(Names.named("bartype1")).to(Bar1Impl.class);
```
@Configuration variable replacement example,
```java
@Configuration(prefix="foo.${name}", parameters={"name"})
public Foo {
private final String name; // match parameter "name"
private int timeout;
public Foo(String name) {
this.name = name;
}
}
```
```properties
foo.abc.timeout=1000
```
```java
Foo foo = new Foo("123");
binder.bindConfig(foo);
```

Add DI named configuration mapping support. Support variable replacements from fields and methods.

---

archaius-core/src/main/java/netflix/archaius/ObservableProperty.java
archaius-core/src/main/java/netflix/archaius/Property.java
archaius-core/src/main/java/netflix/archaius/property/DefaultObservableProperty.java
archaius-core/src/test/java/netflix/archaius/ConfigManagerTest.java
archaius-core/src/test/java/netflix/archaius/property/PropertyTest.java

Add caching to DefaultObservableProperty to optimize the case where client code constantly tries to create the property again.
This change optimizes situations where the Property<?> object is not stored in a variable.  For example,
```java
class SomeClass {
void doSomething() {
config.createProperty("foo.someproperty").asInteger().get(123);
}
}
```
as opposed to the preferred 
```java
class SomeClass {
private Property<Integer> prop;
SomeClass() { 
prop = config.createProperty("foo.someproperty").asInteger();
}
void doSomething() {
prop.get(123)
}
}
```
This PR also moves the default value from asInteger(default) to asInteger().get(default).  This is necessary since caching makes storing the default awkward.

Observable property cache

---

archaius-zookeeper/src/main/java/com/netflix/config/source/ZooKeeperConfigurationSource.java

This commit removes usage of Closeables#closeQuietly(Closeable).
It is removed in future versions of Guava and prevents Archaius
from otherwise being able to run with the latest Guava.
It keeps the same behavior as before and logs the same statement.

Remove usage of Guava method removed in future versions

---

archaius-core/src/main/java/com/netflix/archaius/DefaultAppConfig.java

This pull request resolves issue #274.
When using the DefaultAppConfig with a custom decoder or custom string interpolator, only some of the configurations would receive the decoder or interpolator.

Properly set decoder when using DefaultAppConfig

---

archaius-core/src/main/java/com/netflix/archaius/DefaultConfigLoader.java
archaius-core/src/main/java/com/netflix/archaius/cascade/ConcatCascadeStrategy.java
archaius-core/src/main/java/com/netflix/archaius/config/AbstractConfig.java
archaius-core/src/main/java/com/netflix/archaius/config/CascadingCompositeConfig.java
archaius-core/src/main/java/com/netflix/archaius/config/PrefixedViewConfig.java
archaius-core/src/test/java/com/netflix/archaius/AppConfigTest.java

This pull request is to finish correcting issue #280
Allow the overriding of setDecoder/setStrInterpolator/addListener/removeListener such that configurations that delegate to one or more configurations can assure that those components are properly propagated down to the child(ren) configurations.
I have attempted to make the order of configuration loading be in line with Archaius 1.x as far the configurations sources are handled, but I would greatly appreciate someone taking a second look at the additional library components to make sure that the order is correct. AppConfigTest.testAppAndLibraryLoading() demonstrates the issue that I am speaking of.

Finish correctly setting Decoder/Interpolator logic

---

archaius-core/src/main/java/com/netflix/archaius/DefaultAppConfig.java
archaius-core/src/main/java/com/netflix/archaius/annotations/Configuration.java
archaius-core/src/main/java/com/netflix/archaius/annotations/ConfigurationSource.java
archaius-core/src/main/java/com/netflix/archaius/annotations/DefaultValue.java
archaius-core/src/main/java/com/netflix/archaius/annotations/Embedded.java
archaius-core/src/main/java/com/netflix/archaius/annotations/Value.java
archaius-core/src/main/java/com/netflix/archaius/mapper/DefaultConfigMapper.java
archaius-core/src/test/java/com/netflix/archaius/mapper/DefaultConfigMapperTest.java
archaius-guice/src/main/java/com/netflix/archaius/guice/ArchaiusModule.java
archaius-guice/src/test/java/com/netflix/archaius/guice/ArchaiusModuleTest.java

Additional cleanup
* Argument validation in DefaultAppConfig
* Move annotations to a better package

Fix configuration mapping when there is no prefix

---

archaius-core/src/main/java/com/netflix/archaius/DefaultConfigLoader.java

If there is a syntax error or some other problem in the config
this can be helpful for debugging. E.g. I was seeing a
ClassNotFoundException due to getting different versions of
archaius-core and archaius-guice pulled in and it was swallowing
the exception.

add debug log for failing to load a config file

---

README.md
archaius-guice/README.md

The listed code doesn't work as Provides.guicify expects a
Provider not a Module.

fix docs for config proxy

---

archaius-guice/src/main/java/com/netflix/archaius/guice/ArchaiusModule.java
archaius-guice/src/test/java/com/netflix/archaius/guice/ArchaiusModuleTest.java

Simplify bindings in ArchaiusModule and support an externally provided A
ppConfig implementation instead of allowing ArcahiusModule to be inherited.

Cleanup ArchaiusModule

---

archaius2-core/src/main/java/com/netflix/archaius/AppConfig.java
archaius2-core/src/main/java/com/netflix/archaius/ConfigLoader.java
archaius2-core/src/main/java/com/netflix/archaius/DefaultAppConfig.java
archaius2-core/src/main/java/com/netflix/archaius/DefaultConfigLoader.java
archaius2-core/src/main/java/com/netflix/archaius/config/CascadingCompositeConfig.java
archaius2-core/src/main/java/com/netflix/archaius/config/CompositeConfig.java
archaius2-core/src/main/java/com/netflix/archaius/config/DelegatingConfig.java
archaius2-core/src/test/java/com/netflix/archaius/ConfigManagerTest.java
archaius2-core/src/test/java/com/netflix/archaius/DefaultAppConfigTest.java
archaius2-core/src/test/java/com/netflix/archaius/mapper/DefaultConfigMapperTest.java
archaius2-core/src/test/java/com/netflix/archaius/property/PropertyTest.java
archaius2-guice/src/main/java/com/netflix/archaius/guice/ArchaiusModule.java
archaius2-guice/src/test/java/com/netflix/archaius/guice/ArchaiusModuleTest.java
archaius2-persisted2/src/main/java/com/netflix/archaius/persisted2/JsonPersistedV2Reader.java
archaius2-typesafe/src/test/java/com/netflix/archaius/typesafe/TypesafeConfigLoaderTest.java

Modify DefaultAppConfig to be a DelegatingConfig instead of a CascadingCompositeConfig to avoid exposing all of the CascadingCompositeConfig functionality.
Remove withLoadSystem from ConfigLoader
Expose getting any layer from AppConfig

DefaultAppConfig simplification

---

archaius2-core/src/main/java/com/netflix/archaius/DefaultPropertyFactory.java
archaius2-core/src/main/java/com/netflix/archaius/PropertyContainer.java
archaius2-core/src/main/java/com/netflix/archaius/property/DefaultPropertyContainer.java
archaius2-core/src/main/java/com/netflix/archaius/property/ListenerManager.java
archaius2-core/src/test/java/com/netflix/archaius/config/CompositeConfigTest.java
archaius2-core/src/test/java/com/netflix/archaius/config/ConfigLoaderTest.java
archaius2-core/src/test/java/com/netflix/archaius/config/MapConfigTest.java
archaius2-core/src/test/java/com/netflix/archaius/property/PropertyTest.java

Optimize fast property behavior to use a global dirty flag instead of updating each property individually.  With this change updating ALL fast properties is just a matter of incrementing a single AtomicInteger.  Calling get() on each property will now update the value inline if the global flag has been set.  Listener notification is still done at the time of update but only for the listeners and not for each property.  The assumption here is that there could be 1000's of fast properties but only a handful of listeners.

Fast property update optimization

---

archaius2-typesafe/src/main/java/com/netflix/archaius/typesafe/TypesafeConfig.java
archaius2-typesafe/src/test/java/com/netflix/archaius/typesafe/TypesafeConfigLoaderTest.java
archaius2-typesafe/src/test/java/com/netflix/archaius/typesafe/TypesafeConfigTest.java
archaius2-typesafe/src/test/resources/foo-prod.properties

Certain characters such as `!`, `@`, and `"` need to be
in quotes or escaped to avoid errors:
```
1) Error injecting method, com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path '@environment': Token not allowed in path expression: '@' (Reserved character '@' is not allowed outside quotes) (you can double-quote this token if you really want it here)
at com.netflix.archaius.bridge.StaticAbstractConfiguration.intialize(StaticAbstractConfiguration.java:24)
Caused by: com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path '@environment': Token not allowed in path expression: '@' (Reserved character '@' is not allowed outside quotes) (you can double-quote this token if you really want it here)
at …
```

quote keys for typesafe config

---

archaius2-archaius1-bridge/README.md
archaius2-archaius1-bridge/src/main/java/com/netflix/archaius/bridge/StaticAbstractConfiguration.java
archaius2-archaius1-bridge/src/main/java/com/netflix/archaius/bridge/StaticArchaiusBridgeModule.java
archaius2-archaius1-bridge/src/main/java/com/netflix/archaius/bridge/StaticDeploymentContext.java
archaius2-archaius1-bridge/src/test/java/com/netflix/archaius/bridge/AbstractConfigurationBridgeTest.java

The bridge will now configure the old ConfigurationManager API using install() instead of changing the default implementation via properties, "archaius.default.configuration.class" and "archaius.default.deploymentContext.class".  This way the default AbstractConfiguration implementation may be replaced once the injector is created without throwing exceptions.  Any code accessing ConfigurationManager prior to the injector created will use the default AbstractConfiguration implementation and DeploymentContext.  It is still strongly encouraged to NOT access ConfigurationManager prior to the injector being created.

Fix for #305

---

archaius2-core/src/main/java/com/netflix/archaius/ConfigLoader.java
archaius2-core/src/main/java/com/netflix/archaius/DefaultConfigLoader.java
archaius2-core/src/main/java/com/netflix/archaius/config/CompositeConfig.java
archaius2-core/src/main/java/com/netflix/archaius/readers/PropertiesConfigReader.java
archaius2-core/src/test/java/com/netflix/archaius/config/CompositeConfigTest.java
archaius2-core/src/test/java/com/netflix/archaius/loaders/PropertyConfigReaderTest.java
archaius2-guice/src/main/java/com/netflix/archaius/guice/ArchaiusModule.java
archaius2-guice/src/main/java/com/netflix/archaius/guice/ConfigurationInjectingListener.java
archaius2-typesafe/src/test/java/com/netflix/archaius/typesafe/TypesafeConfigLoaderTest.java

* Modify config loader to load resources as a LinkedHashMap<String, Config> instead of being inconsistent with merging Configs when multiple resources are loaded
* Move @next processing to PropertiesConfigReader instead of forcing it on all ConfigReader's since doing so breaks Typesafe's loading
* Add addConfigs and replaceConfigs to CompositeConfig
* Fix bug where application cascade loading wasn't done correctly

Config loading cleanup

---

build.gradle

Need to upgrade Guava to 16.0 since all Netflix apps are going to upgrade to Guava 16.0

upgrade Guava to 16.0 to comply with Netflix applications

---

archaius-etcd/src/main/java/com/netflix/config/source/EtcdConfigurationSource.java
archaius-etcd/src/test/java/com/netflix/config/source/EtcdConfigurationSourceTest.java
build.gradle
settings.gradle

An Etcd watched configuration source very similar to the ZooKeeperConfigurationSource.
Uses the Boon Etcd client https://github.com/boonproject/boon/blob/master/etcd/README.md.  Seems to be the most widely adopted Etcd client.
Tests included.

EtcdConfigurationSource

---

archaius2-core/src/main/java/com/netflix/archaius/ImmutableProperty.java
archaius2-core/src/main/java/com/netflix/archaius/Property.java
archaius2-core/src/main/java/com/netflix/archaius/ProxyFactory.java
archaius2-core/src/main/java/com/netflix/archaius/annotations/Configuration.java
archaius2-core/src/main/java/com/netflix/archaius/annotations/PropertyInfo.java
archaius2-core/src/main/java/com/netflix/archaius/annotations/PropertyName.java
archaius2-core/src/main/java/com/netflix/archaius/property/DefaultPropertyContainer.java
archaius2-core/src/test/java/com/netflix/archaius/mapper/ProxyFactoryTest.java

* Add PropertyInfo annotation to override the property name when proxying
* Add support for making proxied configuration immutable
* Add toString to proxies configuration interfaces
Example of new features,
```java
@Configuration(immtuable=true) // Once created properties never change
public interface MyConfig {
// Looks for property named "foo.bar" instead of "fooBar" (derived from name)
@PropertyInfo("foo.bar")
public String getFooBar();
// 'is' verb supported in addition to 'get'
public Boolean isEnabled();
}
```

Enhancements to configuration proxy

---

archaius2-core/src/main/java/com/netflix/archaius/ConfigLoader.java
archaius2-core/src/main/java/com/netflix/archaius/ConfigProxyFactory.java
archaius2-core/src/main/java/com/netflix/archaius/DefaultConfigLoader.java
archaius2-core/src/main/java/com/netflix/archaius/cascade/NoCascadeStrategy.java
archaius2-core/src/main/java/com/netflix/archaius/config/CompositeConfig.java
archaius2-core/src/main/java/com/netflix/archaius/inject/ApplicationOverrideLayer.java
archaius2-core/src/main/java/com/netflix/archaius/readers/URLConfigReader.java
archaius2-guice/src/main/java/com/netflix/archaius/guice/ArchaiusConfiguration.java
archaius2-guice/src/main/java/com/netflix/archaius/guice/ArchaiusModule.java
archaius2-guice/src/main/java/com/netflix/archaius/guice/ConfigurationInjectingListener.java
archaius2-guice/src/main/java/com/netflix/archaius/guice/OptionalArchaiusConfiguration.java
archaius2-guice/src/test/java/com/netflix/archaius/guice/ArchaiusModuleTest.java
archaius2-guice/src/test/resources/moduleTest.properties
build.gradle

* Parse properties sources as UTF-8
* Clean up configuration of Archaius for ArchaiusModule to avoid ever having to override ArchaiusModule  to change behavior
* Fix bug in CompositeConfig.from where it always returned an empty configuration
* Add support for library level configuration override via a multi-binding
```java
MapBinder.newMapBinder(binder(), String.class, Config.class, LibrariesLayer.class)
.addBinding("resourceNameToOverride")
.toInstance(MapConfig.from(overrideProps));
```
* Add support for application properties override layer via binding
```java
bind(Config.class).annotatedWith(ApplicationOverrideLayer.class).to(MapConfig.from(overrideProps));
```

Clean up usage of ArchaiusModule

---

archaius2-core/src/main/java/com/netflix/archaius/inject/DefaultsLayer.java
archaius2-guice/src/main/java/com/netflix/archaius/guice/ArchaiusConfiguration.java
archaius2-guice/src/main/java/com/netflix/archaius/guice/ArchaiusModule.java
archaius2-guice/src/main/java/com/netflix/archaius/guice/ConfigSeeders.java
archaius2-guice/src/main/java/com/netflix/archaius/guice/OptionalArchaiusConfiguration.java

Add a new DefaultsLayer that is at the bottom of the hierarchy.  This layer will be used mostly by other modules to set any default values that must be present when necessary for code to function properly.  This is placed at the lowest layer to allow for these configurations to be overwritten.

Adding @DefaultsLayer to AbstractModule

---

archaius2-core/build.gradle
archaius2-core/src/main/java/com/netflix/archaius/ProxyFactory.java
archaius2-core/src/test/java/com/netflix/archaius/ProxyFactoryTest.java

Add support for @Nullable property values.
```java
@Nullable
public getSomeProperty();
```
Add support to use arguments passed to interface getters as replacements for deriving the property names.
```java
@PropertyName(name="foo.${0}.${1}")
public getFoo(String arg0, String arg1);
```

Nullable and argument replacement for configuration proxy

---

archaius2-core/src/main/java/com/netflix/archaius/config/DefaultSettableConfig.java

When copying properties from a Config onto a DefaultSettableConfig copy the uninterpolated value

Fix DefaultSettableConfig interpolation

---

archaius2-core/src/main/java/com/netflix/archaius/ConfigLoader.java
archaius2-core/src/main/java/com/netflix/archaius/DefaultConfigLoader.java
archaius2-core/src/main/java/com/netflix/archaius/readers/PropertiesConfigReader.java
archaius2-core/src/test/java/com/netflix/archaius/config/ConfigLoaderTest.java
archaius2-core/src/test/java/com/netflix/archaius/loaders/PropertyConfigReaderTest.java
archaius2-core/src/test/resources/test-test.properties
archaius2-core/src/test/resources/test-us-east-1.properties
archaius2-core/src/test/resources/test.properties

* Change property file loading behavior to succeed whether the first file exists or not.  Deprecate ConfigLoader.Loader.withFailOnFirst
* Simplify @next support implementation using recursion
* '.properties' is optional for files listed in @next

Improvements to .properties file loading

---

archaius2-core/src/main/java/com/netflix/archaius/readers/URLConfigReader.java

The fix is straightforward. The bug is not loading from the reader.

issue 349 fix the CJK characters issue in Archaius2

---

archaius2-core/src/main/java/com/netflix/archaius/config/AbstractConfig.java

This is actually pretty tricky. There are a couple of issues prior to this. One is at the beginning, the other is at the end of underneath iterator. We need to proceed until we can find one matching prefix at the beginning. At the end, we need to terminate properly by setting the "next" to null at proper place. It's very easy to miss the final one element.

issue #350. Fix the bug in key prefix iterator in Config

---

archaius2-core/src/main/java/com/netflix/archaius/config/polling/FixedPollingStrategy.java

If the polling operation becomes slow, then `scheduleAtFixedRate`
will queue up new requests. This caused a problem for us because
we had an issue with the server side, many requests backed up,
and then when the service was recovered it got hammered with a
much higher rate of requests until the backlog had cleared.
This changes the poller to use `scheduleWithFixedDelay` to avoid
the issue. In general for the properties the overall staleness
seems more important and for the typical case of a quick response
it should make little difference.

2.x poll with fixed delay rather than fixed rate

---

archaius2-api/src/main/java/com/netflix/archaius/api/ListenerSubscription.java
archaius2-api/src/main/java/com/netflix/archaius/api/Property.java
archaius2-api/src/main/java/com/netflix/archaius/api/PropertyFactory.java
archaius2-core/src/main/java/com/netflix/archaius/AbstractProperty.java
archaius2-core/src/main/java/com/netflix/archaius/ConfigMapper.java
archaius2-core/src/main/java/com/netflix/archaius/ConfigProxyFactory.java
archaius2-core/src/main/java/com/netflix/archaius/DefaultPropertyFactory.java
archaius2-core/src/main/java/com/netflix/archaius/DelegatingProperty.java
archaius2-core/src/main/java/com/netflix/archaius/property/DefaultPropertyContainer.java
archaius2-core/src/test/java/com/netflix/archaius/junit/TestHttpServer.java
archaius2-core/src/test/java/com/netflix/archaius/property/PropertyTest.java

Clean up the PropertyFactory and Property APIs to decouple them completely from the Config API so they can be backed by other configuration mechanisms.

Cleanup PropertyFactory API

---

archaius2-archaius1-bridge/src/main/java/com/netflix/archaius/bridge/StaticAbstractConfiguration.java
archaius2-archaius1-bridge/src/test/java/com/netflix/archaius/bridge/DynamicPropertyTest.java

Force getString() to do a .toString() since all the dynamic configuration classes depend on properties being stored as strings

Fix non-string dynamic property bridge

---

archaius2-core/src/main/java/com/netflix/archaius/ConfigProxyFactory.java
archaius2-guice/src/test/java/com/netflix/archaius/guice/ProxyTest.java

Support invoking the an interface method's default implementation when no configuration value is found.
For example,
```java
interface MyConfig {
default int getTimeout() { 
return 1000;
}
}
```
Note that a method may only have a default implementation or a @DefaultValue annotation but not both. An IllegalArgumentException will be thrown if both are present.

Support configuration interface default method

---

archaius2-archaius1-bridge/build.gradle
archaius2-archaius1-bridge/src/main/java/com/netflix/archaius/bridge/StaticAbstractConfiguration.java
archaius2-archaius1-bridge/src/test/java/com/netflix/archaius/bridge/AbstractConfigurationBridgeFailureTest.java

Provide detailed source of how ConfigurationManager was initialized when there was a failure initializing StaticArchaiusBridgeModule.
Stack trace would contain a root cause like this,
```java
Caused by: java.lang.UnsupportedOperationException: **** Remove static reference to ConfigurationManager or FastProperty in this call stack ****
at java.lang.Thread.getStackTrace(Thread.java:1552)
at com.netflix.config.ConfigurationManager.<clinit>(ConfigurationManager.java:91)
at com.netflix.archaius.bridge.AbstractConfigurationBridgeFailureTest$BadModule.<clinit>(AbstractConfigurationBridgeFailureTest.java:25)
at com.netflix.archaius.bridge.AbstractConfigurationBridgeFailureTest.testStaticInModule(AbstractConfigurationBridgeFailureTest.java:43)
... 24 more
```

StaticArchaiusBridgeModule debug error

---

archaius2-core/src/main/java/com/netflix/archaius/readers/PropertiesConfigReader.java

Currently property file loading will stop only at the first file is found.  This can be very problematic when the same property exists in multiple places on the classpath.  Since the file loading order is non deterministic its reasonable to simply load all found resources into a single CompositeConfig.  It is however possible for the same property to be defined in multiple files in which case the first loaded will win.

Load multiple resources with the same resource name

---

archaius-core/src/main/java/com/netflix/config/DynamicProperty.java

This PR is in accordance with this ISSUE: https://github.com/Netflix/archaius/issues/362
I have tried to resolve the issue by setting `isCached` property for the all properties to false, instead of actually doing `flush` for all the properties.

Fix Race Condition for null getProperty

---

archaius2-core/src/main/java/com/netflix/archaius/readers/PropertiesConfigReader.java
archaius2-core/src/test/java/com/netflix/archaius/loaders/PropertyConfigReaderTest.java
archaius2-core/src/test/resources/override-internal-style-next.properties

Add support for the Netflix internal 'netflixconfiguration.properties.nextLoad' directive when loading property files in addition to @next.

Support netflixconfiguration.properties.nextLoad directive in properties files

---

archaius-core/src/test/java/com/netflix/config/ConfigurationManagerTest.java
archaius-core/src/test/java/com/netflix/config/DynamicURLConfigurationTestWithFileURL.java

When I tried to build the project it turned out that the build is system-codepage dependant. In particular given two tests have failed. In can be fixed by telling Java that source files are in given encoding (`javac -encoding utf8`), but perhaps it would be more reliable to use Unicode escaping.

Changed strings that contain Unicode values to corresponding \u-notation

---

archaius2-core/src/main/java/com/netflix/archaius/config/PrefixedViewConfig.java

`containsKey` isn't consistent with other `state.data` accessing methods in `PrefixedViewConfig` as it prefixes the provided `key` with `prefix`.

Fixed PrefixedViewConfig#containsKey (fixes #505)

---

archaius2-api/src/main/java/com/netflix/archaius/Layers.java
archaius2-api/src/main/java/com/netflix/archaius/api/Layer.java
archaius2-api/src/main/java/com/netflix/archaius/api/PropertySource.java
archaius2-api/src/main/java/com/netflix/archaius/api/config/LayeredConfig.java
archaius2-core/src/main/java/com/netflix/archaius/config/AbstractConfig.java
archaius2-core/src/main/java/com/netflix/archaius/config/DefaultLayeredConfig.java
archaius2-core/src/main/java/com/netflix/archaius/config/DefaultSettableConfig.java
archaius2-core/src/main/java/com/netflix/archaius/config/MapConfig.java
archaius2-core/src/test/java/com/netflix/archaius/config/DefaultLayeredConfigTest.java

LayeredConfig will eventually replace CompositeConfig as the top level container for properties.  LayeredConfig simplifies defining multiple override layers that may be added in any order while keeping a well-defined override order.  A set of common layers is defined in the Layers class but additional user defined layers may be defined and added at any time.
This PR is the first in the series of changes through which the LayeredConfig will eventually be the top level config API while keeping backwards compatibility in mind.  Once dependent libraries support a code path for LayeredConfig as the top level API, ArchaiusModule will be updated to use LayeredConfig instead of CompositeConfig.

New LayeredConfig API

---

archaius2-guice/src/main/java/com/netflix/archaius/guice/ConfigurationInjectingListener.java
archaius2-guice/src/test/java/com/netflix/archaius/guice/ConfigurationInjectingListenerTest.java
archaius2-guice/src/test/resources/moduleTest-prod.properties
archaius2-guice/src/test/resources/moduleTest.properties

Fix configuration load order being reversed when processing multiple sources in a ConfigurationSource annotation.  Last one should win.

fix: ConfigurationSource ordering

---

archaius2-api/src/main/java/com/netflix/archaius/api/Config.java
archaius2-api/src/main/java/com/netflix/archaius/api/Property.java
archaius2-api/src/main/java/com/netflix/archaius/api/PropertyContainer.java
archaius2-api/src/main/java/com/netflix/archaius/api/PropertyFactory.java
archaius2-api/src/main/java/com/netflix/archaius/api/PropertyListener.java
archaius2-api/src/main/java/com/netflix/archaius/api/PropertyRepository.java
archaius2-core/src/main/java/com/netflix/archaius/ConfigProxyFactory.java
archaius2-core/src/main/java/com/netflix/archaius/DefaultPropertyFactory.java
archaius2-core/src/main/java/com/netflix/archaius/config/AbstractConfig.java
archaius2-core/src/main/java/com/netflix/archaius/property/DefaultPropertyContainer.java
archaius2-core/src/main/java/com/netflix/archaius/property/ListenerManager.java
archaius2-core/src/test/java/com/netflix/archaius/ProxyFactoryTest.java
archaius2-core/src/test/java/com/netflix/archaius/property/PropertyTest.java
archaius2-guice/src/main/java/com/netflix/archaius/guice/InternalArchaiusModule.java

Refactor the Property/PropertyFactory API so it uses standard interfaces (Supplier, Consumer) and make it composable using an API very similar to Java's Optional.
```
Property<Integer> prop = factory.get("property.name", Integer.class);
Integer currentValue = prop.get();
```
First looks for value of `property.name` and then `property.other` if null.  
```
Property<Integer> prop = factory
.get("property.name", Integer.class)
.orElseGet("property.other");
Integer currentValue = prop.get();
```
```
Property<Integer> prop = factory
.get("property.name", Integer.class)
.orElseGet("property.other")
.orElse(1);
Integer currentValue = prop.get();
```
The listener will only be invoked if the actual value changed. 
```
Property<Integer> prop = factory
.get("property.name", Integer.class) …
```

Refactor Property to use java8 functional APIs

---

archaius-core/src/main/java/com/netflix/config/ConcurrentMapConfiguration.java

_The following issue is currently causing issues in the spring-cloud project, since spring-cloud is currently based on spring 4.x which maintains compatibility with Java 7._
Archaius 0.x claims to be compatible with Java 6 (source and target versions are set to 1.6) but when calling `com.netflix.config.ConcurrentMapConfiguration.getKeys` under Java 7 the following exception occurs:
`Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; at com.netflix.config.ConcurrentMapConfiguration.getKeys(ConcurrentMapConfiguration.java:152)`
This is caused by the fact that Archaius 0.x is compiled using a JDK 8 with source/target set to 1.6 but without a bootclasspath set to 1.6. Therefore you'll run into this issue: …

Archaius 0.x is not compatible with Java 6/7

---

archaius-etcd/src/main/java/com/netflix/config/source/EtcdConfigurationSource.java
build.gradle

Change usage of deprected class com.google.common.base.Object class to com.google.common.base.MoreObjects in archaius-etcd project. Reason of api changes after guava:21.0 released.
MoreObjects from v19 is backward comaptible with guava 16.0 what the archaius-core project uses
Guava release notes:
https://github.com/google/guava/wiki/Release21
Deprecation notification in Objects class:
https://github.com/google/guava/blob/v19.0/guava/src/com/google/common/base/Objects.java#L185

Guava 2x compatibility in archaius-etcd project

---

archaius-core/src/main/java/com/netflix/config/sources/URLConfigurationSource.java

It would be nice to have the property value `archaius.configurationSource.defaultFileName` available/shared with other Java classes which would like to re-use it.

The property value for config file path is extracted into the separate variable.

---

archaius-core/src/main/java/com/netflix/config/PropertyWrapper.java

Update the callbacks collection in PropertyWrapper to be thread safe
(similar to DynamicProperty). Remove runnable entries from callbacks
collection after removing from DynamicProperty.

Update PropertyWrapper to be thread safe.

---

archaius-etcd/src/main/java/com/netflix/config/source/EtcdConfigurationSource.java

when etcd instance is empty (i.e. no keys configured) configNode.getNodes() returns null. This avoids throwing NPE, while preserving a consistent behavior

fix: prevent possible NPE

---

archaius2-api/src/main/java/com/netflix/archaius/api/Property.java
archaius2-core/src/main/java/com/netflix/archaius/DefaultPropertyFactory.java
archaius2-core/src/test/java/com/netflix/archaius/property/PropertyTest.java

Sample usage
```
Property<Integer> prop = registry.get("foo", Integer.class);
Subscription subscription = prop.onChange((newValue) -> System.out.println("new value: " + newValue));
```
To unsubscribe
````
subscription.unsubscribe();
```

API to unsubscribe to property change notifications

---

archaius2-core/src/main/java/com/netflix/archaius/ConfigProxyFactory.java
archaius2-core/src/test/java/com/netflix/archaius/ProxyFactoryTest.java

The ConfigProxyFactory currently attempts to bind a Map to multiple properties where the key is the next name part of a property prefix and the value maps to one or more properties.  This implementation turned out to be very error-prone and confusing to use.  
This PR making binding to Maps just like all other collections where the Map is parsed from a single property values with the format. `k1=v1,k2=v2,...`.

Property proxying of Map type

---

archaius2-core/src/main/java/com/netflix/archaius/interpolate/CommonsStrInterpolator.java
archaius2-core/src/test/java/com/netflix/archaius/config/InterpolationTest.java

This change enables interpolation of other properties in addition to static defaults.  For example, the property value `${someProperty:${someOtherProperty:staticDefault}}` will first replace the value of `someProperty`, if not found, will use the value of `someOtherProperty` and if that's not found replace with the static value `staticDefault`

Allow for interpolation in default values

---

.travis.yml
archaius2-api/src/main/java/com/netflix/archaius/api/Config.java
archaius2-api/src/main/java/com/netflix/archaius/api/Decoder.java
archaius2-api/src/main/java/com/netflix/archaius/api/PropertyRepository.java
archaius2-api/src/main/java/com/netflix/archaius/api/TypeConverter.java
archaius2-core/src/main/java/com/netflix/archaius/ConfigProxyFactory.java
archaius2-core/src/main/java/com/netflix/archaius/DefaultDecoder.java
archaius2-core/src/main/java/com/netflix/archaius/DefaultPropertyFactory.java
archaius2-core/src/main/java/com/netflix/archaius/config/AbstractConfig.java
archaius2-core/src/main/java/com/netflix/archaius/converters/ArrayTypeConverterFactory.java
archaius2-core/src/main/java/com/netflix/archaius/converters/DefaultCollectionsTypeConverterFactory.java
archaius2-core/src/main/java/com/netflix/archaius/converters/DefaultTypeConverterFactory.java
archaius2-core/src/main/java/com/netflix/archaius/converters/EnumTypeConverterFactory.java
archaius2-core/src/main/java/com/netflix/archaius/exceptions/ConverterNotFoundException.java
archaius2-core/src/test/java/com/netflix/archaius/DefaultDecoderTest.java
archaius2-core/src/test/java/com/netflix/archaius/ProxyFactoryTest.java
archaius2-guice/src/test/java/com/netflix/archaius/guice/ProxyTest.java
archaius2-guice/src/test/resources/log4j.properties
archaius2-test/src/main/java/com/netflix/archaius/test/Archaius2TestConfig.java

- Introduce a new TypeConverter contract through which the decoder may be extended.
- Capture array, enum and typed collection conversions via TypeConverter.Factory implementations
- Support typed collections, such as `Map<String, Long>`, when using ConfigProxyFactory without having to wrap them in a custom type

Improved support for collection types

---

.travis.yml

Closes #572 for 2.x.
As mentioned in the issue, this setting was depracted over a year ago
and should be removed.

travis: Remove deprecated sudo setting.

---

archaius2-core/src/main/java/com/netflix/archaius/config/DefaultCompositeConfig.java
archaius2-core/src/main/java/com/netflix/archaius/config/DefaultLayeredConfig.java
archaius2-core/src/main/java/com/netflix/archaius/config/DependentConfigListener.java
archaius2-core/src/main/java/com/netflix/archaius/config/PrefixedViewConfig.java
archaius2-core/src/main/java/com/netflix/archaius/config/PrivateViewConfig.java
archaius2-core/src/test/java/com/netflix/archaius/config/CompositeConfigTest.java
archaius2-core/src/test/java/com/netflix/archaius/config/DefaultLayeredConfigTest.java
archaius2-core/src/test/java/com/netflix/archaius/config/PrefixedViewTest.java
archaius2-core/src/test/java/com/netflix/archaius/config/PrivateViewTest.java

Views created that depend on other views (Composite, Layered, and Prefixed) create listeners on the source view that update themselves. This reference to themselves prevents GC until the source view is abandoned, meaning creating unused dependent views is a memory and performance leak. This applies the WeakReference logic from the PrivateView to the other dependent view types in order to fix this leak.
There is a small bug in PrefixedViewConfig where we supposedly allow prefixes of form "foo" or "foo.", but any prefix of form "foo." will actually still assume form "foo", meaning that configs such as "foo.bar" would, in the prefixed view, be taken as configs of type "ar" instead of the expected "bar".  I'll address this in a followup change in case there is anyone relying on this behavior.

Fix memory leak caused by anonymous listeners in abandoned views

---

archaius2-core/src/main/java/com/netflix/archaius/config/PrefixedViewConfig.java
archaius2-core/src/test/java/com/netflix/archaius/config/PrefixedViewTest.java

Current behavior for PrefixedViewConfig is that, for a prefix of form "foo." we expect configs of form "foo..bar", which is unusual.
We update PrefixedViewConfig to properly accept prefixes of form "foo." and expect configs of form "foo.bar".

Update PrefixedViewConfig to properly handle trailing dot case
