Netflix/archaius

archaius-core/src/main/java/com/netflix/config/ConfigurationBasedDeploymentContext.java
Fixes a typo in com.netflix.config.ConfigurationBasedDeploymentContext
=> fixes #211

archaius-core/src/main/java/netflix/archaius/Config.java, archaius-core/src/main/java/netflix/archaius/DefaultConfigLoader.java, archaius-core/src/main/java/netflix/archaius/config/AbstractConfig.java, archaius-core/src/main/java/netflix/archaius/config/CompositeConfig.java, archaius-core/src/main/java/netflix/archaius/config/EnvironmentConfig.java, archaius-core/src/main/java/netflix/archaius/config/MapConfig.java, archaius-core/src/main/java/netflix/archaius/config/PollingDynamicConfig.java, archaius-core/src/main/java/netflix/archaius/config/PrefixedViewConfig.java, archaius-core/src/main/java/netflix/archaius/config/SimpleDynamicConfig.java, archaius-core/src/main/java/netflix/archaius/config/SystemConfig.java, archaius-core/src/main/java/netflix/archaius/interpolate/CommonsStrInterpolatorFactory.java, archaius-typesafe/src/main/java/netflix/archaius/typesafe/TypesafeConfig.java
=> Default fail if first resource fails to load

archaius-commons-configuration/src/main/java/netflix/archaius/commons/CommonsToConfig.java, archaius-legacy/src/main/java/com/netflix/config/ConfigurationBasedDeploymentContext.java, archaius-legacy/src/main/java/com/netflix/config/ConfigurationManager.java, archaius-legacy/src/main/java/com/netflix/config/DefaultLegacyConfigurationManager.java, archaius-legacy/src/main/java/com/netflix/config/DefaultLegacyRootConfigurationFactory.java, archaius-legacy/src/main/java/com/netflix/config/DeploymentContext.java, archaius-legacy/src/main/java/com/netflix/config/LegacyConfigurationManager.java, archaius-legacy/src/main/java/com/netflix/config/LegacyRootConfigurationFactory.java, archaius-legacy/src/main/java/com/netflix/config/SimpleDeploymentContext.java, archaius-legacy/src/main/test/resources/test.properties, archaius-legacy/src/test/java/com/netflix/config/ConfigurationManagerTest.java, build.gradle, settings.gradle
New sub-project to bridge Apache Commons Configuration
New sub-project to provide backwards compatibility support for the legacy API
=> Backwards compatibility sub-project to old api

archaius-core/src/main/java/netflix/archaius/CachingDynamicConfigObserver.java, archaius-core/src/main/java/netflix/archaius/DefaultAppConfig.java, archaius-core/src/main/java/netflix/archaius/DefaultDecoder.java, archaius-core/src/main/java/netflix/archaius/ObservablePropertyFactory.java, archaius-core/src/main/java/netflix/archaius/PrefixedObservablePropertyFactory.java, archaius-core/src/main/java/netflix/archaius/mapper/DefaultConfigMapper.java, archaius-core/src/main/java/netflix/archaius/mapper/annotations/Configuration.java, archaius-core/src/test/java/netflix/archaius/ConfigManagerTest.java, archaius-core/src/test/java/netflix/archaius/DefaultDecoderTest.java, archaius-core/src/test/java/netflix/archaius/property/PropertyTest.java, archaius-guice/src/main/java/netflix/archaius/guice/ArchaiusModule.java, archaius-guice/src/test/java/netflix/archaius/guice/ArchaiusModuleTest.java
* Fix DefaultDecoder.  
* Support primitive types in DefaultDecoder.  
* @Configuration methods to make field or method mapping optional.  
* Disable field mapping by default.  
* @Configuration method to specify PostConfigure method to invoke after configuration mapping.   
* Utility method to create a guice binding for a proxied configuration interface
=> Misc fixes

archaius-core/src/main/java/com/netflix/archaius/config/AbstractConfig.java, archaius-core/src/main/java/com/netflix/archaius/config/DelegatingConfig.java, archaius-core/src/main/java/com/netflix/archaius/config/PollingDynamicConfig.java, archaius-core/src/main/java/com/netflix/archaius/config/PollingStrategy.java, archaius-core/src/main/java/com/netflix/archaius/config/polling/FixedPollingStrategy.java, archaius-core/src/main/java/com/netflix/archaius/config/polling/ManualPollingStrategy.java, archaius-core/src/main/java/com/netflix/archaius/config/polling/PollingResponse.java, archaius-core/src/main/java/com/netflix/archaius/interpolate/CommonsStrInterpolatorFactory.java, archaius-core/src/main/java/com/netflix/archaius/loaders/PropertiesConfigReader.java, archaius-core/src/main/java/com/netflix/archaius/readers/URLConfigReader.java, archaius-core/src/test/java/com/netflix/archaius/config/PollingDynamicConfigTest.java
* When interpolating values if key not found return ${key}
* Add PollingResponse in prep for increment updates
=> Misc cleanup and bug fixes

archaius-persisted2/src/main/java/com/netflix/archaius/persisted2/loader/HTTPStreamLoader.java
* don't close stream, it is returned and needs to be
consumed by the reader
* treat 304 as a noop rather than throwing an exception
* since it doesn't actually support deflate, remove that
from the accept-encoding list
=> fix http stream loader

README.md, archaius2-core/src/main/java/com/netflix/archaius/config/SystemConfig.java, archaius2-guice/README.md, archaius2-persisted2/build.gradle, archaius2-persisted2/src/main/java/com/netflix/archaius/persisted2/DefaultPersisted2ClientConfig.java, archaius2-persisted2/src/main/java/com/netflix/archaius/persisted2/Persisted2ClientConfig.java, archaius2-persisted2/src/main/java/com/netflix/archaius/persisted2/Persisted2ConfigProvider.java, archaius2-persisted2/src/test/java/com/netflix/archaius/persisted2/PlatformServiceTest.java
Persisted2ClientProvider and documentation to setup a Persisted2 client as the OverrideLayer
=> Guice module to setup up Persisted2 client

archaius2-archaius1-bridge/src/main/java/com/netflix/archaius/bridge/AbstractConfigurationBridge.java, archaius2-archaius1-bridge/src/main/java/com/netflix/archaius/bridge/StaticAbstractConfiguration.java, archaius2-archaius1-bridge/src/main/java/com/netflix/archaius/bridge/StaticArchaiusBridgeModule.java, archaius2-archaius1-bridge/src/test/java/com/netflix/archaius/bridge/DynamicPropertyTest.java, archaius2-core/src/main/java/com/netflix/archaius/DefaultConfigLoader.java, archaius2-core/src/main/java/com/netflix/archaius/config/CompositeConfig.java, archaius2-core/src/main/java/com/netflix/archaius/exceptions/ConfigAlreadyExistsException.java, archaius2-core/src/test/resources/log4j.properties, archaius2-guice/src/main/java/com/netflix/archaius/guice/ArchaiusModule.java, archaius2-guice/src/main/java/com/netflix/archaius/guice/ConfigurationInjectingListener.java
Fix order of cascading config for application layer
Fix NPE in configuration mapping/binding guice listener
=> Support for DynamicPropertyFactory backed by archaius2

archaius2-archaius1-bridge/src/main/java/com/netflix/archaius/bridge/StaticArchaiusBridgeModule.java, archaius2-archaius1-bridge/src/main/java/com/netflix/archaius/bridge/StaticDeploymentContext.java, archaius2-archaius1-bridge/src/test/java/com/netflix/archaius/bridge/AbstractConfigurationBridgeTest.java, archaius2-core/src/main/java/com/netflix/archaius/DefaultDecoder.java, archaius2-core/src/main/java/com/netflix/archaius/property/DefaultPropertyContainer.java, archaius2-guice/src/main/java/com/netflix/archaius/guice/ArchaiusModule.java, archaius2-guice/src/test/java/com/netflix/archaius/guice/ArchaiusModuleTest.java
Misc fixes/cleanup for guice bindings
=> Support arrays in DefaultDecoder

archaius2-core/src/main/java/com/netflix/archaius/DefaultDecoder.java, archaius2-core/src/main/java/com/netflix/archaius/ProxyFactory.java, archaius2-core/src/main/java/com/netflix/archaius/config/AbstractConfig.java, archaius2-core/src/main/java/com/netflix/archaius/property/DefaultPropertyContainer.java, archaius2-core/src/test/java/com/netflix/archaius/ProxyFactoryTest.java
* Support proxying methods from inherited interfaces
* Remove incorrect setting of default value when parsing non-primitive types in fast properties
* Delegate parsing of various types to Decoder
=> Inheritance support in configuration proxying

README.md, archaius2-api/src/main/java/com/netflix/archaius/api/StrInterpolator.java, archaius2-core/build.gradle, archaius2-core/src/main/java/com/netflix/archaius/ConfigProxyFactory.java, archaius2-core/src/main/java/com/netflix/archaius/DefaultConfigLoader.java, archaius2-core/src/main/java/com/netflix/archaius/property/DefaultPropertyContainer.java, archaius2-core/src/test/java/com/netflix/archaius/DefaultConfigLoaderTest.java, archaius2-core/src/test/java/com/netflix/archaius/ProxyFactoryTest.java, archaius2-core/src/test/java/com/netflix/archaius/property/PropertyTest.java, archaius2-core/src/test/java/com/netflix/archaius/readers/URLConfigReaderTest.java, archaius2-guice/src/main/java/com/netflix/archaius/guice/ArchaiusModule.java
Cleaned up some unused code and added unit tests after running local code coverage. Please check if the code I deleted is indeed not used. Other than doing a search within the project and in Stash across projects I didn't have a good way of checking.
=> README updates, tests and code clean up on 2.x

archaius2-core/src/main/java/com/netflix/archaius/property/DefaultPropertyContainer.java, archaius2-core/src/test/java/com/netflix/archaius/DefaultPropertyContainerTest.java
Fix DefaultPropertyContainer so that it actually caches the new value and version stamp
=> Fix property caching

archaius2-core/src/main/java/com/netflix/archaius/ConfigProxyFactory.java, archaius2-core/src/main/java/com/netflix/archaius/DefaultPropertyFactory.java
make MethodInvoker interface public
open visibility to methods on DefaultPropertyFactory for extension
expose Config object backing ConfigProxyFactory
=> Visibility changes to support some extension

archaius2-core/src/main/java/com/netflix/archaius/DefaultDecoder.java, archaius2-core/src/test/java/com/netflix/archaius/DefaultDecoderTest.java, build.gradle
period and duration are especially needed
=> add handling for java 8 time classes and miscellaneous others

archaius2-guice/src/main/java/com/netflix/archaius/guice/ArchaiusModule.java
These properties should only be set when using StaticArchaiusBridgeModule
=> DONT set archaius1 properties in ArchaiusModule

archaius2-test/src/main/java/com/netflix/archaius/test/ConfigInterfaceTest.java, archaius2-typesafe/build.gradle, archaius2-typesafe/src/main/java/com/netflix/archaius/typesafe/TypesafeConfig.java, archaius2-typesafe/src/test/java/com/netflix/archaius/typesafe/TypesafeConfigTest.java
Getting a property was throwing an exception, even in the case where a default value was provided.  This is not the correct behavior.  Also started adding some more tests for this kind of thing.
=> Fix Typesafe exception handling.

archaius2-core/src/main/java/com/netflix/archaius/ConfigProxyFactory.java, archaius2-core/src/test/java/com/netflix/archaius/ProxyFactoryTest.java
Fix default methods for collection types not being called for ConfigProxyFactory
=> Honor default methods for collections

archaius2-core/src/main/java/com/netflix/archaius/property/ListenerManager.java, archaius2-core/src/test/java/com/netflix/archaius/property/PropertyTest.java
Remove unnecessary eager notification on change when a listener is registered
=> Fix eager change notification

.travis.yml, archaius-core/src/main/java/com/netflix/config/AbstractPollingScheduler.java, archaius-core/src/main/java/com/netflix/config/DynamicConfiguration.java, archaius-core/src/main/java/com/netflix/config/PollListener.java, archaius-core/src/test/java/com/netflix/config/PollingSourceTest.java, build.gradle
We need more complete notifications for configuration reloading, specifically we need an event before and after loading to control fast property behavior.
=> Dynamic loading notification

archaius2-core/src/main/java/com/netflix/archaius/ConfigProxyFactory.java, archaius2-core/src/test/java/com/netflix/archaius/ProxyFactoryTest.java
Parametrized properties with a default method fail because the code tries to create a MethodHandle to a method with no arguments. And, even if the method lookup is fixed, getting the default value for the property fails because the arguments to the call are not propagated.
=> Fixed interaction of default methods and parametrized properties.

archaius2-core/src/main/java/com/netflix/archaius/ConfigProxyFactory.java
Avoid allocating an Optional and lmabda on every call to the MethodInvoker returned by createScalarProperty.
=> Avoid Optional and lambda allocation in MethodInvoker
